# Generated by Django 5.2.9 on 2025-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tool_options_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_file',
            field=models.FileField(blank=True, help_text='Upload Zip/Script', null=True, upload_to='tools/zips/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_url',
            field=models.URLField(blank=True, help_text='External link', max_length=500, null=True),
        ),
    ]
