# Generated by Django 5.2.9 on 2025-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tool_tool_file_alter_tool_tool_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tool_file',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tool_url',
        ),
        migrations.AddField(
            model_name='tool',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
