# Generated by Django 5.2.9 on 2025-12-16 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tool_name_remove_tool_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tools_files/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
